services:

  # Development service - includes volume mount for live development
  app-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ../server:/app
    # Override the command to run the dev script instead of the built app
    command: npm run start

